### ISSUE TITLE
500 when requesting the results as JSON

### ISSUE THREAD

**Issue by afeld** [18F/compliance-viewer#15]
Example:

https://compliance-viewer.18f.gov/results/api-data-gov/0pu1icJJdIet1_NBY3Gph65Eq32ha6A6?format=json

Also, thoughts about using an extension of `.json` rather than `format=json`?

**Comment by DavidEBest** [comment]
Okay. The problem is https://github.com/18F/compliance-viewer/blob/master/app.rb#L51 . This should be the new ENV format used elsewhere. Obviously there should also be a test that exercises the json retrieval functionality.

I went with a querystring instead of an extension because the version ids can include `.` inside them. I had one case (with older data) that ended with a period, which created some weird file names. I'd certainly prefer the extension method, but I didn't see a clean way to work around it. 

Another option would be to just ditch the version ids. They are pretty ugly, and could conceivably be replaced with something that has meaning, like a timestamp. The version retrieval code would more complicated; we'd need to iterate over the `bucket.object_versions` to find the appropriate version.
